# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cfe6a7f4e44b5a38e4d9805e92665661a99bac232d4c5e0f59aed181cd80b0215f984052216444854ac379c26b8f24b481b3aed6e71d2b8f8c03b3fb03501dcc
  google_client_id: 373103577628-68b458bn8debs3bsrj66ef107lr657pp.apps.googleusercontent.com
  google_client_secret: R3OdqKXs8K6ZBQTeGVWJRf1v
test:
  secret_key_base: f1bcda27c717f8fe66861ecd7aef4a1110bcfd0b2a7c417e32503e5d258e8818e05dcfd102fda599d7cbd886caa6ba2e8b54730528e4536276eb5388fa801285

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
